---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-app
  namespace: my-demo
  labels:
    app: validation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-app
  template:
    metadata:
      labels:
        app: validation-app
    spec:
      containers:
      - name: validation-app
        image: validation-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: validation-app-service
  namespace: my-demo
  labels:
    app: validation-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: validation-app